### ISSUE TITLE
/* prettier-ignore */ inside CSS file not working

### ISSUE THREAD

**Issue by timonson** [prettier/vim-prettier#227]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current/expected behavior?**

I try to run the command `Prettier` on the following code inside a `.css` file:

```css
/* prettier-ignore */
#sub-slogan {
  font-family:${opts.font || "brandon"},sans-serif;
  font-size: 1.25rem;
  font-weight: 400;
  color: #9babb4;
  text-align: center;
  line-height: 1.5;
  width: 100%;
  margin: auto;
}
```

Current behavior: `Prettier: failed to parse buffer`

Expected behavior: `Prettier` works while ignoring this rule set.

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

1.0.0-alpha

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

1.19.1

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

prettier

**Did this work in previous versions of vim-prettier and/or prettier ?**

I am not sure
